#!/usr/bin/python3
# SPDX-License-Identifier: MIT
import sys
sys.path.insert(0, "/usr/lib/tab-companion")
from tab_companion.update_core import main
try:
    main()
except Exception as error:
    print(error, file=sys.stderr)
    sys.exit(1)
