# SPDX-License-Identifier: MIT
# Spanish, French, German, Italian, European Portuguese.
TRANSLATIONS = {
    "For 20 seconds after authorization, this test records the cover keyboard’s key presses, releases and repeats, including keys that could reveal what you type. Do not enter passwords or sensitive information. The report is saved locally in your diagnostics folder; nothing is sent automatically.": ("Durante los 20 segundos posteriores a la autorización, esta prueba registra las pulsaciones, liberaciones y repeticiones de teclas de la funda, que pueden revelar lo que escribes. No introduzcas contraseñas ni información sensible. El informe se guarda localmente en tu carpeta de diagnósticos; no se envía nada automáticamente.", "Pendant les 20 secondes suivant l’autorisation, ce test enregistre les pressions, relâchements et répétitions des touches de la coque clavier, qui peuvent révéler ce que vous saisissez. Ne saisissez ni mot de passe ni information sensible. Le rapport est enregistré localement dans votre dossier de diagnostic ; rien n’est envoyé automatiquement.", "Dieser Test zeichnet nach der Autorisierung 20 Sekunden lang Tastendrücke, Loslassen und Wiederholungen der Tastaturhülle auf. Diese Daten können deine Eingaben offenlegen. Gib keine Passwörter oder vertraulichen Informationen ein. Der Bericht wird lokal im Diagnoseordner gespeichert; nichts wird automatisch gesendet.", "Per 20 secondi dopo l’autorizzazione, questa prova registra pressioni, rilasci e ripetizioni dei tasti della cover, che possono rivelare ciò che scrivi. Non inserire password o informazioni sensibili. Il rapporto viene salvato localmente nella cartella di diagnostica; non viene inviato nulla automaticamente.", "Durante os 20 segundos após a autorização, este teste regista as teclas premidas, libertadas e repetidas da capa, que podem revelar o que escreves. Não introduzas palavras-passe nem informações sensíveis. O relatório é guardado localmente na pasta de diagnósticos; nada é enviado automaticamente."),
    "Recording key presses for 20 seconds. Do not type sensitive information.": ("Registrando pulsaciones durante 20 segundos. No escribas información sensible.", "Enregistrement des touches pendant 20 secondes. Ne saisissez pas d’informations sensibles.", "Tastendrücke werden 20 Sekunden lang aufgezeichnet. Gib keine vertraulichen Informationen ein.", "Registrazione dei tasti per 20 secondi. Non scrivere informazioni sensibili.", "A registar teclas durante 20 segundos. Não escrevas informações sensíveis."),
    "Report saved to: {path}": ("Informe guardado en: {path}", "Rapport enregistré dans : {path}", "Bericht gespeichert unter: {path}", "Rapporto salvato in: {path}", "Relatório guardado em: {path}"),
    "Review the recorded key presses before sharing this report.": ("Revisa las pulsaciones registradas antes de compartir este informe.", "Vérifiez les touches enregistrées avant de partager ce rapport.", "Prüfe die aufgezeichneten Tastendrücke, bevor du diesen Bericht teilst.", "Controlla i tasti registrati prima di condividere questo rapporto.", "Revê as teclas registadas antes de partilhares este relatório."),
    "Retry": ("Reintentar", "Réessayer", "Erneut versuchen", "Riprova", "Tentar novamente"),
    "Save keyboard cover logs…": ("Guardar registros de la funda con teclado…", "Enregistrer les journaux de la coque clavier…", "Protokolle der Tastaturhülle speichern…", "Salva i registri della cover con tastiera…", "Guardar registos da capa com teclado…"),
    "Diagnose keyboard and touchpad connection problems.": ("Diagnostica problemas de conexión del teclado y el touchpad.", "Diagnostiquer les problèmes de connexion du clavier et du pavé tactile.", "Verbindungsprobleme mit Tastatur und Touchpad untersuchen.", "Diagnostica i problemi di connessione di tastiera e touchpad.", "Diagnosticar problemas de ligação do teclado e do touchpad."),
    "Collect keyboard cover logs?": ("¿Recopilar registros de la funda con teclado?", "Recueillir les journaux de la coque clavier ?", "Protokolle der Tastaturhülle erfassen?", "Raccogliere i registri della cover con tastiera?", "Recolher registos da capa com teclado?"),
    "Keep the cover connected and reproduce the problem for about 20 seconds. The report includes device information and connection errors, but no typed keys. You choose where to save it; nothing is sent automatically.": ("Mantén la funda conectada y reproduce el problema durante unos 20 segundos. El informe incluye información del dispositivo y errores de conexión, pero no las teclas pulsadas. Tú eliges dónde guardarlo; no se envía nada automáticamente.", "Gardez la coque connectée et reproduisez le problème pendant environ 20 secondes. Le rapport contient les informations de l’appareil et les erreurs de connexion, mais pas les touches saisies. Vous choisissez où l’enregistrer ; rien n’est envoyé automatiquement.", "Lass die Hülle angeschlossen und stelle das Problem etwa 20 Sekunden lang nach. Der Bericht enthält Geräteinformationen und Verbindungsfehler, aber keine gedrückten Tasten. Du wählst den Speicherort; nichts wird automatisch gesendet.", "Tieni la cover collegata e riproduci il problema per circa 20 secondi. Il rapporto include informazioni sul dispositivo ed errori di connessione, ma non i tasti premuti. Scegli tu dove salvarlo; non viene inviato nulla automaticamente.", "Mantém a capa ligada e reproduz o problema durante cerca de 20 segundos. O relatório inclui informações do dispositivo e erros de ligação, mas não as teclas premidas. Escolhes onde o guardar; nada é enviado automaticamente."),
    "Collect logs": ("Recopilar registros", "Recueillir les journaux", "Protokolle erfassen", "Raccogli registri", "Recolher registos"),
    "Collecting keyboard cover logs…": ("Recopilando registros de la funda con teclado…", "Collecte des journaux de la coque clavier…", "Protokolle der Tastaturhülle werden erfasst…", "Raccolta dei registri della cover con tastiera…", "A recolher registos da capa com teclado…"),
    "Keep the cover connected and try its keyboard and touchpad.": ("Mantén la funda conectada y prueba su teclado y touchpad.", "Gardez la coque connectée et essayez son clavier et son pavé tactile.", "Lass die Hülle angeschlossen und teste Tastatur und Touchpad.", "Tieni la cover collegata e prova la tastiera e il touchpad.", "Mantém a capa ligada e testa o teclado e o touchpad."),
    "Could not collect keyboard cover logs": ("No se pudieron recopilar los registros de la funda", "Impossible de recueillir les journaux de la coque clavier", "Protokolle der Tastaturhülle konnten nicht erfasst werden", "Impossibile raccogliere i registri della cover", "Não foi possível recolher os registos da capa"),
    "Keyboard cover logs saved": ("Registros de la funda guardados", "Journaux de la coque clavier enregistrés", "Protokolle der Tastaturhülle gespeichert", "Registri della cover salvati", "Registos da capa guardados"),
    "Send this report with the cover model and a description of the problem.": ("Envía este informe junto con el modelo de la funda y una descripción del problema.", "Envoyez ce rapport avec le modèle de la coque et une description du problème.", "Sende diesen Bericht zusammen mit dem Modell der Hülle und einer Beschreibung des Problems.", "Invia questo rapporto con il modello della cover e una descrizione del problema.", "Envia este relatório com o modelo da capa e uma descrição do problema."),
    "Could not save keyboard cover logs": ("No se pudieron guardar los registros de la funda", "Impossible d’enregistrer les journaux de la coque clavier", "Protokolle der Tastaturhülle konnten nicht gespeichert werden", "Impossibile salvare i registri della cover", "Não foi possível guardar os registos da capa"),
    "Save": ("Guardar", "Enregistrer", "Speichern", "Salva", "Guardar"),
}
